{
    'name': 'Income Tax Calculator',
    'summary': """This module adds the custom user groups in the users""",
    'version': '15.0.2.4 29-june',
    'description': """This module adds the custom user groups in the users""",
    'author': 'PMCS',
    "license": "AGPL-3",
    'sequence': 10,
    'company': 'prime minds consulting pvt ltd',
    'website': 'http://www.primeminds.com',
    'category': 'Accounting',
    'depends': ['base', 'hr', 'om_hr_payroll', 'hr_contract', 'hr_holidays', 'user_access'],
    'data': [
        'security/user_access.xml',
        'security/ir.model.access.csv',
        'wizards/YTOD_report_wizard.xml',
        'views/view_rec_history.xml',
        'views/view_res_background.xml',
        'views/view_res_family.xml',
        'views/view_res_language.xml',
        'views/view_res_nominee.xml',
        'views/res_company_view.xml',
        'views/chapter_vi_a_views.xml',
        'views/section_24_views.xml',
        'views/city_type_conf.xml',
        'views/section_10_views.xml',
        'views/section_16_views.xml',
        'views/section_80c_views.xml',
        'views/other_incomes_sources.xml',
        'views/overall_limits_views.xml',
        'views/taxable_income_views.xml',
        'views/tax_slab_views.xml',
        'views/employee_tds.xml',
        'views/it_return_views.xml',
        'views/hr_salary_rule.xml',
        'views/hr_employee_views.xml',
        'views/hr_payslip.xml',
        'views/hr_contract.xml',
        'reports/it_worksheet_for_employee.xml',
        'reports/menu.xml',
        'views/it_returns_new.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
