# -*- coding: utf-8 -*-
{
    'name': 'HR Employee',
    'version': '15.0.0.1',
    'summary': 'Inherit fields module',
    'sequence': 2,
    'category': 'Tools',
    'description': 'Inherit fields module',
    'website': '',
    'depends': ['base', 'hr'],
    'data': [
        "security/ir.model.access.csv",
        "views/view_hr_employee.xml",
        "views/view_rec_history.xml",
        "views/view_res_background.xml",
        "views/view_res_family.xml",
        "views/view_res_language.xml",
        "views/view_res_nominee.xml",
        "reports/hr_employee_report.xml",
        "reports/hr_employee_template.xml",
        "reports/hr_employee_background_report.xml",
        "reports/hr_employee_background_template.xml",
        "reports/hr_employee_history.xml",
        "reports/hr_employee_history_template.xml",
        "reports/confirmation_letter.xml",
        "reports/confirmation_letter_template.xml",
        "reports/hr_employee_induction_form.xml",
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}