from . import rec_history
from . import hr_salary_rule
from . import res_background
from . import res_family
from . import res_language
from . import res_nominee
from . import hr_employee
from . import it_return
from . import chapter_vi_a
from . import section_24
from . import section_10
from . import section_16
from . import section_80c
from . import taxable_income
from . import tax_slab
from . import other_incomes_sources
from . import overall_limits
from . import hr_payslip
from . import city_type_conf
from . import res_company
from . import employee_tds
from . import hr_contract
